<?xml version='1.0' encoding='US-ASCII' standalone='no' ?>
<!DOCTYPE ffparams [
<!ELEMENT ffparams (header_parameter_list, (data_list)+,
(udf_invocation_table)?, (site_tuple_list | param_tuple_list)*,
(pair_list)*, (group_list)*)>

<!-- The header parameter list contains per system information.  Each -->
<!-- parameter has associated name, type, and symbolic_constant -->
<!-- attributes.  If symbolic_constant="true" then it is intended that -->
<!-- the parameter so labeled is to be treated as a symbolic constant -->
<!-- for use by downstream applications-->
<!ELEMENT header_parameter_list (header_parameter)+>
<!ELEMENT header_parameter (#PCDATA)>
<!ATTLIST header_parameter param_id ID #REQUIRED>
<!ATTLIST header_parameter type (char | double | int) "char">
<!ATTLIST header_parameter symbolic_constant (true | false) "false">

<!-- The data_list contains a list of type_ids that are used -->
<!-- for a variety of purposes, including molecule types and molecule -->
<!-- instances as well as LJ types.   These types may have -->
<!-- parameter values associated with them which are defined in the -->
<!-- type_parameter_list. Information about what type_id is -->
<!-- bound to a particular site_id must be conveyed via a -->
<!-- site_parameter_ref. It is required that type_ids consist of the -->
<!-- type_class string with an underscore and number appended -->
<!ELEMENT data_list (data_title, data_parameter_list, (data_record)+)>
<!ATTLIST data_list data_class_prepend ID #REQUIRED>
<!ELEMENT data_title (#PCDATA)>
<!ELEMENT data_parameter_list (data_parameter_spec)*>
<!ATTLIST data_parameter_list param_prepend ID #REQUIRED>
<!ELEMENT data_parameter_spec (#PCDATA)>
<!ATTLIST data_parameter_spec param_id ID #REQUIRED>
<!ATTLIST data_parameter_spec type (char | double | int | idref) "char">
<!ATTLIST data_parameter_spec ref_prepend IDREF #IMPLIED>
<!ELEMENT data_record ((data_parameter | data_parameter_ref))*>
<!ATTLIST data_record data_id ID #REQUIRED>
<!ELEMENT data_parameter (#PCDATA)>
<!ATTLIST data_parameter param_ref IDREF #REQUIRED>
<!ELEMENT data_parameter_ref EMPTY>
<!ATTLIST data_parameter_ref param_ref IDREF #REQUIRED>
<!ATTLIST data_parameter_ref ref_ptr IDREF #REQUIRED>
<!-- The invocation table contains a list of all the user defined -->
<!-- functions required for this system and pointers to tuples of -->
<!-- sites and parameters required for each UDF   -->
<!ELEMENT udf_invocation_table (udf_invocation_rec)*>
<!ELEMENT udf_invocation_rec EMPTY>
<!ATTLIST udf_invocation_rec udf_id ID #REQUIRED>
<!ATTLIST udf_invocation_rec site_tuple_ref IDREF #REQUIRED>
<!ATTLIST udf_invocation_rec param_tuple_ref IDREF #IMPLIED>

<!-- The site tuple list contains a collection of site_id tuples that are -->
<!-- used by one or more udfs.  The order of the tuples in this list -->
<!-- must correspond to the order of the tuples in the corresponding -->
<!-- param_tuple_list -->
<!ELEMENT site_tuple_list (site_tuple)+>
<!ATTLIST site_tuple_list id ID #REQUIRED>
<!ELEMENT site_tuple (site)+>
<!ELEMENT site EMPTY>
<!ATTLIST site site_ref IDREF #REQUIRED>
<!ATTLIST site site_ordinal CDATA #REQUIRED>

<!-- The param tuple list contains a collection of parameter tuples -->
<!-- that are used by one or more udfs.  The order of the tuples in -->
<!-- this list must correspond to the order of the tuples in the -->
<!-- corresponding site_tuple_list.  This list also has the usual -->
<!-- parameter specification block at the beginning.  The element -->
<!-- value of the param_spec element is the name of the parameter -->
<!ELEMENT param_tuple_list (param_spec_list, (param_tuple)+)>
<!ATTLIST param_tuple_list id ID #REQUIRED>
<!ELEMENT param_spec_list (param_spec)+>
<!ATTLIST param_spec_list param_prepend NMTOKEN #REQUIRED>
<!ELEMENT param_spec (#PCDATA)>
<!ATTLIST param_spec param_id ID #REQUIRED>
<!ATTLIST param_spec type (double | int) "double">
<!ELEMENT param_tuple (param)+>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param param_ref IDREF #REQUIRED>

<!-- The pair list contains a list of pair interaction parameters for -->
<!-- each pair of the associated types-->
<!ELEMENT pair_list (pair_parameter_list, (pair_record)+)>
<!ATTLIST pair_list type_class_prepend IDREF #REQUIRED>
<!ELEMENT pair_parameter_list (pair_parameter_spec)+>
<!ATTLIST pair_parameter_list param_prepend ID #REQUIRED>
<!ELEMENT pair_parameter_spec (#PCDATA)>
<!ATTLIST pair_parameter_spec param_id ID #REQUIRED>
<!ATTLIST pair_parameter_spec type (char | double | int) "char">
<!ELEMENT pair_record (pair_parameter)+>
<!ATTLIST pair_record type_ref_1 IDREF #REQUIRED>
<!ATTLIST pair_record type_ref_2 IDREF #REQUIRED>
<!ELEMENT pair_parameter (#PCDATA)>
<!ATTLIST pair_parameter param_ref IDREF #REQUIRED>

<!-- User defined groups contain group information and a list of group -->
<!-- members specified by site_id-->
<!ELEMENT group_list (group_info, (group_member)+)>
<!ATTLIST group_list group_id ID #REQUIRED>
<!ATTLIST group_list group_class CDATA #REQUIRED>
<!ELEMENT group_info (#PCDATA)>
<!ELEMENT group_member EMPTY>
<!ATTLIST group_member site_ref IDREF #REQUIRED>
]>
<ffparams>
<header_parameter_list>
<header_parameter param_id="ff_family" type="char" symbolic_constant="false">OPLSAA</header_parameter>
<header_parameter param_id="ff_spec" type="char" symbolic_constant="false">OPLSAA</header_parameter>
<header_parameter param_id="charge14" type="int" symbolic_constant="true">1</header_parameter>
<header_parameter param_id="charge14scale" type="double" symbolic_constant="true">0.5</header_parameter>
<header_parameter param_id="lj14" type="int" symbolic_constant="true">1</header_parameter>
<header_parameter param_id="lj14scale" type="double" symbolic_constant="true">0.5</header_parameter>
<header_parameter param_id="torsioninput" type="int" symbolic_constant="false">1</header_parameter>
<header_parameter param_id="improper" type="int" symbolic_constant="false">1</header_parameter>
<header_parameter param_id="ureybradley" type="int" symbolic_constant="false">0</header_parameter>
<header_parameter param_id="grouping" type="int" symbolic_constant="false">1</header_parameter>
<header_parameter param_id="water" type="char" symbolic_constant="false">SPC</header_parameter>
<header_parameter param_id="units" type="char" symbolic_constant="false">CHEM</header_parameter>
<header_parameter param_id="ChargeConversion" type="double" symbolic_constant="true">SciConst::OldChargeConversion</header_parameter>
<header_parameter param_id="TimeConversionFactor" type="double" symbolic_constant="true">SciConst::OldTimeConversion</header_parameter>
</header_parameter_list>

<data_list data_class_prepend="mt_">
 <data_title>molecule_type</data_title>
 <data_parameter_list param_prepend="mtp_">
    <data_parameter_spec param_id="mtp_1" type="char">class</data_parameter_spec>
 </data_parameter_list>
 <data_record data_id="mt_1">
    <data_parameter param_ref="mtp_1">protein</data_parameter>
 </data_record>
 <data_record data_id="mt_2">
    <data_parameter param_ref="mtp_1">solvent</data_parameter>
 </data_record>
 <data_record data_id="mt_3">
    <data_parameter param_ref="mtp_1">dna</data_parameter>
 </data_record>
 <data_record data_id="mt_4">
    <data_parameter param_ref="mtp_1">rna</data_parameter>
 </data_record>
 <data_record data_id="mt_5">
    <data_parameter param_ref="mtp_1">ligand</data_parameter>
 </data_record>
 <data_record data_id="mt_6">
    <data_parameter param_ref="mtp_1">other_polymer</data_parameter>
 </data_record>
 <data_record data_id="mt_7">
    <data_parameter param_ref="mtp_1">other</data_parameter>
 </data_record>
</data_list>

<data_list data_class_prepend="mn_">
<data_title>molecule_name</data_title>
 <data_parameter_list param_prepend="mnp_">
   <data_parameter_spec param_id="mnp_1" type="char">name</data_parameter_spec>
   <data_parameter_spec param_id="mnp_2" type="idref" ref_prepend="mt_">molecule_class</data_parameter_spec>
 </data_parameter_list>
 <data_record data_id="mn_1">
    <data_parameter param_ref="mnp_1">myprotein</data_parameter>
    <data_parameter_ref param_ref="mnp_2" ref_ptr="mt_1"/>
 </data_record>
 </data_list>

<data_list data_class_prepend="m_">
<data_title>molecule</data_title>
 <data_parameter_list param_prepend="mp_">
    <data_parameter_spec param_id="mp_1" type="idref" ref_prepend="mn_">molecule_type</data_parameter_spec>
 </data_parameter_list>
 <data_record data_id="m_1">
   <data_parameter_ref param_ref="mp_1" ref_ptr="mn_1"/>
 </data_record>
 </data_list>

<data_list data_class_prepend="cc_">
<data_title>chemical_component</data_title>
<data_parameter_list param_prepend="ccp_">
<data_parameter_spec param_id="ccp_1" type="char">component_name</data_parameter_spec>
</data_parameter_list>
    <data_record data_id="cc_1">
      <data_parameter param_ref="ccp_1" >TYR</data_parameter>
    </data_record>
    <data_record data_id="cc_2">
      <data_parameter param_ref="ccp_1" >GLY</data_parameter>
    </data_record>
    <data_record data_id="cc_3">
      <data_parameter param_ref="ccp_1" >PHE</data_parameter>
    </data_record>
    <data_record data_id="cc_4">
      <data_parameter param_ref="ccp_1" >MET</data_parameter>
    </data_record>
</data_list>

<data_list data_class_prepend="at_">
<data_title>atom_name</data_title>
<data_parameter_list param_prepend="atp_">
<data_parameter_spec param_id="atp_1" type="char">atom_name</data_parameter_spec>
</data_parameter_list>
    <data_record  data_id="at_1"> 
      <data_parameter param_ref="atp_1">N</data_parameter>
    </data_record>
    <data_record  data_id="at_2"> 
      <data_parameter param_ref="atp_1">1H</data_parameter>
    </data_record>
    <data_record  data_id="at_3"> 
      <data_parameter param_ref="atp_1">2H</data_parameter>
    </data_record>
    <data_record  data_id="at_4"> 
      <data_parameter param_ref="atp_1">3H</data_parameter>
    </data_record>
    <data_record  data_id="at_5"> 
      <data_parameter param_ref="atp_1">CA</data_parameter>
    </data_record>
    <data_record  data_id="at_6"> 
      <data_parameter param_ref="atp_1">HA</data_parameter>
    </data_record>
    <data_record  data_id="at_7"> 
      <data_parameter param_ref="atp_1">CB</data_parameter>
    </data_record>
    <data_record  data_id="at_8"> 
      <data_parameter param_ref="atp_1">1HB</data_parameter>
    </data_record>
    <data_record  data_id="at_9"> 
      <data_parameter param_ref="atp_1">2HB</data_parameter>
    </data_record>
    <data_record  data_id="at_10"> 
      <data_parameter param_ref="atp_1">CG</data_parameter>
    </data_record>
    <data_record  data_id="at_11"> 
      <data_parameter param_ref="atp_1">CD1</data_parameter>
    </data_record>
    <data_record  data_id="at_12"> 
      <data_parameter param_ref="atp_1">HD1</data_parameter>
    </data_record>
    <data_record  data_id="at_13"> 
      <data_parameter param_ref="atp_1">CE1</data_parameter>
    </data_record>
    <data_record  data_id="at_14"> 
      <data_parameter param_ref="atp_1">HE1</data_parameter>
    </data_record>
    <data_record  data_id="at_15"> 
      <data_parameter param_ref="atp_1">CZ</data_parameter>
    </data_record>
    <data_record  data_id="at_16"> 
      <data_parameter param_ref="atp_1">OH</data_parameter>
    </data_record>
    <data_record  data_id="at_17"> 
      <data_parameter param_ref="atp_1">HH</data_parameter>
    </data_record>
    <data_record  data_id="at_18"> 
      <data_parameter param_ref="atp_1">CE2</data_parameter>
    </data_record>
    <data_record  data_id="at_19"> 
      <data_parameter param_ref="atp_1">HE2</data_parameter>
    </data_record>
    <data_record  data_id="at_20"> 
      <data_parameter param_ref="atp_1">CD2</data_parameter>
    </data_record>
    <data_record  data_id="at_21"> 
      <data_parameter param_ref="atp_1">HD2</data_parameter>
    </data_record>
    <data_record  data_id="at_22"> 
      <data_parameter param_ref="atp_1">C</data_parameter>
    </data_record>
    <data_record  data_id="at_23"> 
      <data_parameter param_ref="atp_1">O</data_parameter>
    </data_record>
    <data_record  data_id="at_24"> 
      <data_parameter param_ref="atp_1">H</data_parameter>
    </data_record>
    <data_record  data_id="at_25"> 
      <data_parameter param_ref="atp_1">1HA</data_parameter>
    </data_record>
    <data_record  data_id="at_26"> 
      <data_parameter param_ref="atp_1">2HA</data_parameter>
    </data_record>
    <data_record  data_id="at_27"> 
      <data_parameter param_ref="atp_1">HZ</data_parameter>
    </data_record>
    <data_record  data_id="at_28"> 
      <data_parameter param_ref="atp_1">1HG</data_parameter>
    </data_record>
    <data_record  data_id="at_29"> 
      <data_parameter param_ref="atp_1">2HG</data_parameter>
    </data_record>
    <data_record  data_id="at_30"> 
      <data_parameter param_ref="atp_1">SD</data_parameter>
    </data_record>
    <data_record  data_id="at_31"> 
      <data_parameter param_ref="atp_1">CE</data_parameter>
    </data_record>
    <data_record  data_id="at_32"> 
      <data_parameter param_ref="atp_1">1HE</data_parameter>
    </data_record>
    <data_record  data_id="at_33"> 
      <data_parameter param_ref="atp_1">2HE</data_parameter>
    </data_record>
    <data_record  data_id="at_34"> 
      <data_parameter param_ref="atp_1">3HE</data_parameter>
    </data_record>
    <data_record  data_id="at_35"> 
      <data_parameter param_ref="atp_1">OXT</data_parameter>
    </data_record>
</data_list>

<data_list data_class_prepend="lj_">
<data_title>Lennard_Jones_Types</data_title>
<data_parameter_list param_prepend="ljt_">
</data_parameter_list>
  <data_record data_id="lj_1"></data_record>
  <data_record data_id="lj_2"></data_record>
  <data_record data_id="lj_3"></data_record>
  <data_record data_id="lj_4"></data_record>
  <data_record data_id="lj_5"></data_record>
  <data_record data_id="lj_6"></data_record>
  <data_record data_id="lj_7"></data_record>
  <data_record data_id="lj_8"></data_record>
  <data_record data_id="lj_9"></data_record>
  <data_record data_id="lj_10"></data_record>
  <data_record data_id="lj_11"></data_record>
  <data_record data_id="lj_12"></data_record>
  <data_record data_id="lj_13"></data_record>
  <data_record data_id="lj_14"></data_record>
  <data_record data_id="lj_15"></data_record>
</data_list>

<data_list data_class_prepend="lj14_">
<data_title>Lennard_Jones_14_Types</data_title>
<data_parameter_list param_prepend="ljt14_">
</data_parameter_list>
  <data_record data_id="lj14_1"></data_record>
  <data_record data_id="lj14_2"></data_record>
  <data_record data_id="lj14_3"></data_record>
  <data_record data_id="lj14_4"></data_record>
  <data_record data_id="lj14_5"></data_record>
  <data_record data_id="lj14_6"></data_record>
  <data_record data_id="lj14_7"></data_record>
  <data_record data_id="lj14_8"></data_record>
  <data_record data_id="lj14_9"></data_record>
  <data_record data_id="lj14_10"></data_record>
  <data_record data_id="lj14_11"></data_record>
  <data_record data_id="lj14_12"></data_record>
  <data_record data_id="lj14_13"></data_record>
  <data_record data_id="lj14_14"></data_record>
  <data_record data_id="lj14_15"></data_record>
</data_list>

<data_list data_class_prepend="site_">
<data_title>site_list</data_title>
  <data_parameter_list param_prepend="sp_">
     <data_parameter_spec param_id="sp_1" type="double">mass</data_parameter_spec>
     <data_parameter_spec param_id="sp_2" type="double">charge</data_parameter_spec>
     <data_parameter_spec param_id="sp_3" type="idref" ref_prepend="m_">molecule</data_parameter_spec>
     <data_parameter_spec param_id="sp_4" type="idref" ref_prepend="cc_">chemical_component</data_parameter_spec>
     <data_parameter_spec param_id="sp_5" type="idref" ref_prepend="at_">atom_name</data_parameter_spec>
     <data_parameter_spec param_id="sp_6" type="idref" ref_prepend="lj_">lennard_jones_type</data_parameter_spec>
     <data_parameter_spec param_id="sp_7" type="idref" ref_prepend="lj14_">lennard_jones_14_type</data_parameter_spec>
     <data_parameter_spec param_id="sp_8" type="int">atomic_number</data_parameter_spec>
  </data_parameter_list>
 <data_record data_id="site_1">
   <data_parameter param_ref="sp_1">14.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.3000*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_1"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_1"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_1"/>
   <data_parameter param_ref="sp_8">7</data_parameter>
 </data_record>
 <data_record data_id="site_2">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.3300*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_2"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_2"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_2"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_3">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.3300*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_3"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_2"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_2"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_4">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.3300*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_4"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_2"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_2"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_5">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(0.2500*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_5"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_3"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_3"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_6">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.0600*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_6"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_4"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_4"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_7">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.0050*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_7"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_5"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_5"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_8">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.0600*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_8"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_4"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_4"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_9">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.0600*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_9"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_4"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_4"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_10">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_10"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_6"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_6"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_11">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_11"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_6"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_6"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_12">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_12"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_7"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_7"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_13">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_13"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_6"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_6"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_14">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_14"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_7"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_7"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_15">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(0.1500*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_15"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_6"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_6"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_16">
   <data_parameter param_ref="sp_1">16.0000</data_parameter>
   <data_parameter param_ref="sp_2">(-0.5850*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_16"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_8"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_8"/>
   <data_parameter param_ref="sp_8">8</data_parameter>
 </data_record>
 <data_record data_id="site_17">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.4350*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_17"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_9"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_9"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_18">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_18"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_6"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_6"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_19">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_19"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_7"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_7"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_20">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_20"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_6"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_6"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_21">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.1150*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_21"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_7"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_7"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_22">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(0.5000*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_22"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_10"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_10"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_23">
   <data_parameter param_ref="sp_1">16.0000</data_parameter>
   <data_parameter param_ref="sp_2">(-0.5000*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_1"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_23"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_11"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_11"/>
   <data_parameter param_ref="sp_8">8</data_parameter>
 </data_record>
 <data_record data_id="site_24">
   <data_parameter param_ref="sp_1">14.0100</data_parameter>
   <data_parameter param_ref="sp_2">(-0.5000*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_2"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_1"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_12"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_12"/>
   <data_parameter param_ref="sp_8">7</data_parameter>
 </data_record>
 <data_record data_id="site_25">
   <data_parameter param_ref="sp_1">1.0080</data_parameter>
   <data_parameter param_ref="sp_2">(0.3000*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_2"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_24"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_13"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_13"/>
   <data_parameter param_ref="sp_8">1</data_parameter>
 </data_record>
 <data_record data_id="site_26">
   <data_parameter param_ref="sp_1">12.0100</data_parameter>
   <data_parameter param_ref="sp_2">(0.0800*ChargeConversion)</data_parameter>
   <data_parameter_ref param_ref="sp_3" ref_ptr="m_1"/>
   <data_parameter_ref param_ref="sp_4" ref_ptr="cc_2"/>
   <data_parameter_ref param_ref="sp_5" ref_ptr="at_5"/>
   <data_parameter_ref param_ref="sp_6" ref_ptr="lj_3"/>
   <data_parameter_ref param_ref="sp_7" ref_ptr="lj14_3"/>
   <data_parameter param_ref="sp_8">6</data_parameter>
 </data_record>
 <data_record data_id="site_27">